renovate.json
- 今の設定だと renovate により peerDeps もアップデートされるようになっている
- ref: https://github.com/hatena/eslint-config-hatena/pull/6/commits/b7cf804a2e5290c45566b7faf59ccf074ef3ec31
- peerDeps をアップデートするとライブラリを利用可能なプロジェクトが意図せず減ってしまうので困る
- そのため peerDeps を renovate の管理外にしたい
=> peerDeps を renovate の管理外に

+prettier.js, README.md, docs/integration.md, package.json, yarn.lock
- 様々な理由により eslint のエラーに prettier のエラーを含めるようにするのは推奨されていない
- https://zenn.dev/teppeis/articles/2021-02-eslint-prettier-vscode#%E8%83%8C%E6%99%AF
- ので、やめてしまう
=> eslint のエラーに prettier のエラーを含めないように

docs/usage.md, index.js
- `parserOptions.ecmaVersion` を指定し忘れていた
- `env` だけだと ES2020 で追加されたグローバルオブジェクトが読み込まれるが、新しい構文には対応できていなかった
=> ES2020 の構文がパースできない問題を修正

.github/workflows/nodejs.yml, .github/workflows/publish.yml
This is to address the following issue:
[GitHub Actions: Deprecating save-state and set-output commands | GitHub Changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I executed the following command.
```
npx set-env-to-github_env
```
=> Replace set-output for the GitHub Workflows to address the deprecation warnings

README.md, package.json, yarn.lock
***breaking***
ref. https://github.com/mizdra/eslint-config-mizdra/pull/165
- 利用側で個別にインストール・アップデートする手間がかからないようにする
- バージョンは現在の最新版と互換性のある範囲としておく
- これまでユーザーが個別にインストールしていたバージョンと異なる可能性があるため, メジャーバージョンアップ相当の変更となる
- 元々 `peerDependencies` の記述をそのまま使うと常に最新をインストールすることになり, プラグインのメジャーバージョンアップの際にルールの設定が妥当であることを保証できないので, `^` でバージョン指定をする
=> プラグインなどを peerDependencies から dependencies にする

.npmrc, package.json, yarn.lock
GitHub Packages 経由では、`yarn install` する際に GitHub PAT が必要で、開発の障壁が高くなってしまいます。
- ref: [GitHub Packages を npm install するための手段あれこれ - mizdra's blog](https://www.mizdra.net/entry/2021/03/31/235055)
一方で、`@hatena/prettier-config-hatena` は public リポジトリかつ事前ビルドが不要なパッケージであるため、 [GitHub Packages を npm install するための手段あれこれ - mizdra's blog](https://www.mizdra.net/entry/2021/03/31/235055) の案4のような方法でインストールすることができます。この方法であれば PAT がなくともインストールできるようです。
`npm outdated` や `npm update` の対象外となるデメリットがありますが、eslint-config-hatena では renovate を使って依存関係のアップデートをしており、 Renovate は URL 指定でインストールした npm package もアップデートしてくれるので、問題になることは無いだろうと思っています。
=> `@hatena/prettier-config-hatena` を URL 指定でインストールする

lib/rules/javascript.js
closes #53
[`eqeqeq`](https://eslint.org/docs/latest/rules/eqeqeq) を有効化します.
`== null` を例外的に許容する設定も可能ですが, eslint-config-hatena を利用しているリポジトリを調査したところ多くは見られなかったので, 一律で禁止としてしまってもよいでしょう
=> eqeqeq を有効化

eslint.config.js, package.json, pnpm-lock.yaml
元々 TypeScript でビルドすることを想定して安定版への依存を追加していましたが, ビルドすることがなくなって不要になっていました
=> stable 版の dependency を削除

docs/usage.md, lib/classic/javascript.js, lib/classic/react.js, lib/classic/typescript.js, lib/config/index.js, lib/rules/index.js, lib/rules/react.js, lib/types.d.ts, package.json, pnpm-lock.yaml
https://github.com/hatena/eslint-config-hatena/pull/79 での変更を, v2 に合わせる形で取り込みました.
Flat Config 版にも同様の変更を入れています.
反対に, 旧来の .eslintrc 形式は ESLint v9 で deprecated になることから, .eslintrc のみに影響があるような変更はあえて取り込んでいません. 具体的には以下の 2 つです
- https://github.com/hatena/eslint-config-hatena/pull/79/commits/7778b2484f5871f0267143d2058b3f2ad302910a
- もはや積極的にリファクタリングしたいことはないだろうと考えています
- https://github.com/hatena/eslint-config-hatena/pull/79/commits/65dbefdec8c224e7ebdf165352ee5e5f45a5240b
- 今互換性を崩して .eslintrc のまま変更を強いるよりは, Flat Config に移行してもらった方が良いだろうと思っています
=> 設定を現代に合わせる & 扱いやすくするために更新

package.json, pnpm-lock.yaml
- peerDependencies の情報の更新
- ESLint は v8.57.0 以降をサポート範囲としました
- Prettier, TypeScript はこのパッケージから直接要求する必要はないため削除しました
- peerDependenciesMeta の記述は不要そうだったため削除しました
- optional: false であればデフォルトなので記述は不要. autoInstall は各種パッケージマネージャのドキュメントに記述を見つけられませんでした
- dependencies の更新
- eslint-plugin-import などを, 依存ライブラリをまとめて更新しました
=> dependencies の手入れ

lib/rules/typescript.js
外部 API のリクエスト / レスポンスや HTTP ヘッダなど, snake_case や kebab-case のプロパティを扱う機会は多いため, デフォルトではこれらを許容する設定にします
=> naming-convention ルールの調整

docs/usage.md, lib/config/index.js
https://typescript-eslint.io/packages/parser#projectservice
まだ運用例が少ないため, ひとまずオプトインで導入します
=> typescript-eslint の projectService をオプトインできるようにする

package.json
The key order in the `exports` field is important, and `default` should be the last one.
ref. https://nodejs.org/api/packages.html#conditional-exports
=> fix: fix ordering in the exports field

eslint.config.js, lib/config/index.js, package.json, pnpm-lock.yaml
- resolver の設定を[ドキュメント](https://github.com/import-js/eslint-plugin-import?tab=readme-ov-file#typescript)の通りに行う 
- [eslint-config-next](https://github.com/vercel/next.js/blob/c53ef9b3cd63845ba8165c720d84669e97d0b513/packages/eslint-config-next/index.js#L107-L123) の設定も一部取り込む
=> eslint-plugin-import の設定を更新

configtest/next/eslint.config.mjs, configtest/next/run.sh, configtest/next/src/index.tsx, configtest/next/tsconfig.json, docs/usage.md, lib/config/index.js, lib/rules/index.js, lib/rules/next.js, lib/types.d.ts, package.json, pnpm-lock.yaml
- Next.js 14 時点では eslint-config-next は Flat Config や ESLint v9 に対応していない様子
- プラグインの互換性の問題を解消した上で eslint-config-next 相当の設定を提供できていると便利そう
=> feat: Next.js 向けの設定を追加

lib/config/index.js, package.json, pnpm-lock.yaml
相対パスは何かと壊れやすいので, [eslint-config-next](https://github.com/vercel/next.js/blob/c53ef9b3cd63845ba8165c720d84669e97d0b513/packages/eslint-config-next/index.js#L107-L123) を参考に [`require.resolve`](https://nodejs.org/api/modules.html#requireresolverequest-options) を使ってモジュールのパスをあらかじめ解決しておく
=> parser や resolver を require.resolve で解決する

lib/config/index.js, lib/index.d.ts
https://github.com/hatena/eslint-config-hatena/pull/141 に対応する型定義の追加が漏れていました
=> 型定義の更新漏れを修正

lib/config/index.js, package.json, pnpm-lock.yaml
- typescript-eslint の更新による TypeScript 5.6 のサポート
- @next/eslint-plugin-next, eslint-plugin-react-hooks の更新による ESLint v9 の正式サポート
=> 依存パッケージの更新

lib/config/index.js, lib/config/next.js, lib/config/react.js, lib/index.d.ts, package.json, pnpm-lock.yaml
これまでは React / Next.js 向けの設定は全体で有効にする必要がありましたが, monorepo で一つの eslint.config.js を使う場合など, ディレクトリごとに細かく有効 / 無効を制御したい場合には不向きでした.
``` ts
import config from "@hatena/eslint-config-hatena/flat";
export default config({ react: true });
// または
export default config({ next: "strict" });
```
そこで新たに `config.react()`, `config.next()` を追加し, 同様の設定をディレクトリごとに行えるようにします.
(上記の方法も引き続きサポートされます.)
``` ts
import config from "@hatena/eslint-config-hatena/flat";
export default config({}, [
// foo 以下では React 向けの設定を有効化する
{
files: ["foo/**/*.{ts,tsx}"],
extends: config.react(),
},
// bar 以下では Next.js 向けの設定を有効化する (React 向けの設定も内包)
{
files: ["bar/**/*.{ts,tsx}"],
extends: config.next({ strict: true }),
},
]);
```
=> React / Next.js 向けの設定を個別に利用可能にする

lib/config/index.js, lib/config/next.js, lib/config/react.js, lib/types.d.ts, package.json, pnpm-lock.yaml
- Replace `tseslint.config()` with `defineConfig()`, which is expected to become the standard way to define flat configs.
- [Evolving flat config with extends - ESLint - Pluggable JavaScript Linter](https://eslint.org/blog/2025/03/flat-config-extends-define-config-global-ignores/)
- Also use types provided by eslint itself.
=> feat: use defineConfig from @eslint/config-helpers
